### ISSUE TITLE
Add executable symlink to $PREFIX/condabin

### ISSUE THREAD

**Issue by isuruf** [conda-forge/mamba-feedstock#13]
This is to make sure that mamba installed in root environment is found when other environments are activated.

**Comment by wolfv** [comment]
cool! That's exactly what i am looking for. Do you know what the best practice is to create this link? from the setup.py file?

**Comment by isuruf** [comment]
@wolfv, not from setup.py. Creating the symlink in unix in build.sh would work. In windows you can create a simple `mamba.bat` file that forwards all arguments to the actual mamba executable.

**Comment by wolfv** [comment]
I'm not sure what should happen if mamba isn't installed in the root environment... I guess I could anyways add a non functional condabin.

Otherwise I was thinking about adding a pre-link script to check whether $PREFIX/condabin exists. However the pre-link script gives a very ugly warning. The post-link shouldn't add any files. So I guess that's not going to work nicely. I might do your suggestion!

**Comment by wolfv** [comment]
we're doing this now! thanks for the suggestion.
